spring.datasource.url=jdbc:mysql://localhost:3306/help_community
spring.datasource.username=root
spring.datasource.password=root1521

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081